# Generated by Django 4.2.2 on 2023-07-03 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_familia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventario',
            new_name='Inventario_familia',
        ),
    ]
